name: Java CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: setup-graalvm
      uses: rtc11/setup-graalvm@1.0
      with:
        args: https://github.com/oracle/graal/releases/download/vm-19.2.0.1/graalvm-ce-linux-amd64-19.2.0.1.tar.gz
    - name: Build with Maven
      run: mvn package -Pnative -Dnative-image.docker-build=true
